force-app/main/default/objects/LM_ArtigoCD__c/LM_ArtigoCD__c.object-meta.xml
<CustomObject>
    <label>Artigo</label>
    <nameField>
        <label>Código LM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artigos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Designacao__c.field-meta.xml
<CustomField>
    <fullName>Designacao__c</fullName>
    <label>Designação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Certificado de Devolução</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Artigos</relationshipLabel>
    <relationshipName>Artigos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Peso_Total__c.field-meta.xml
<CustomField>
    <fullName>Peso_Total__c</fullName>
    <formula>Quantidade__c *  Peso_Unitario__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Peso Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Peso_Unitario__c.field-meta.xml
<CustomField>
    <fullName>Peso_Unitario__c</fullName>
    <label>Peso Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/PVP__c.field-meta.xml
<CustomField>
    <fullName>PVP__c</fullName>
    <label>PVP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A Entregar</fullName>
            </value>
            <value>
                <fullName>A Recolher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LM_ArtigoCD__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <formula>Quantidade__c * PVP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LM_OrderCustomController.cls
public with sharing class LM_OrderCustomController {
	public Id recordId {get; set;}

    public LM_OrderCustomController(ApexPages.StandardController controller) {
        
    }
    
    public List<OrderItem> getOrderItems(){
        recordId = ApexPages.currentPage().getParameters().get('id');
        List<OrderItem> orderItems = [SELECT Id, Quantity, PricebookEntry.Name, Type__c, OrderId, TotalPrice, UnitPrice FROM OrderItem WHERE OrderId =:recordId ];   
        return orderItems;
    }

    public List<LM_ArtigoCD__c> getArtigosRecolha(){
        recordId = ApexPages.currentPage().getParameters().get('id');
        List<LM_ArtigoCD__c> artigosRecolha = [SELECT Id, Name, Designacao__c, Peso_Unitario__c, PVP__c, Quantidade__c, Peso_Total__c, Valor__c, Tipo__c FROM LM_ArtigoCD__c WHERE Order__c =:recordId AND Tipo__c = 'A Recolher'];   
        return artigosRecolha;
    }

    public List<LM_ArtigoCD__c> getArtigosEntrega(){
        recordId = ApexPages.currentPage().getParameters().get('id');
        List<LM_ArtigoCD__c> artigosEntrega = [SELECT Id, Name, Designacao__c, Peso_Unitario__c, PVP__c, Quantidade__c, Peso_Total__c, Valor__c, Tipo__c FROM LM_ArtigoCD__c WHERE Order__c =:recordId AND Tipo__c = 'A Entregar' ];   
        return artigosEntrega;
    }
	 
}