force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Registo de Integração</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Registo #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registos de Integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Sistema Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Pyxis</fullName>
            </value>
            <value>
                <fullName>SOP</fullName>
            </value>
            <value>
                <fullName>MDM</fullName>
            </value>
            <value>
                <fullName>L2Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLogDeleteBatch.cls
/**
 * @description       : TO DELETE INTEGRATION LOGS DAILY
 * @author            : miguel.lopes
 * @group             :
 * @create date on    : 2026-02-10 10:14:16
 * @last modified by  : miguel.lopes
 **/
public with sharing class IntegrationLogDeleteBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Integer total = [SELECT COUNT() FROM IntegrationLog__c];
        Integer maxKeep = 1000;

        if (total <= maxKeep) {
            // Nothing to delete
            return Database.getQueryLocator([SELECT Id FROM IntegrationLog__c WHERE SourceSystem__c = 'Pyxis']);
        }

        Integer toDelete = total - maxKeep;
        String query = 'SELECT Id FROM IntegrationLog__c WHERE SourceSystem__c = \'Pyxis\' ORDER BY CreatedDate ASC LIMIT ' + toDelete;
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<IntegrationLog__c> scope) {
        delete scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Integration log cleanup completed');
    }
}