force-app/main/default/objects/Lead/fields/Canal_de_Interacao__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Interacao__c</fullName>
    <inlineHelpText>Scheduler Online - cliente agenda online em autonomia (independente se o cliente escolhe fazer presencial ou online)                    
Scheduler Loja - cliente vai à loja, o agendamento é feito pela loja (independente se o cliente escolhe fazer presencial ou online)                 
Scheduler Telefone - cliente liga a pedir para agendar                   
Loja - venda simples em loja (não é agendamento de projeto)                   
VAD - venda simples pela VAD (não é agendamento de projeto)</inlineHelpText>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduler Online</fullName>
            </value>
            <value>
                <fullName>Scheduler Loja</fullName>
            </value>
            <value>
                <fullName>Scheduler Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>VAD</fullName>
            </value>
            <value>
                <fullName>Profissional</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Importação</fullName>
                <isActive>false</isActive>
                <label>Importação</label>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Online</fullName>
                <isActive>false</isActive>
                <label>Online</label>
            </value>
            <value>
                <fullName>Redes Sociais</fullName>
                <isActive>false</isActive>
                <label>Redes Sociais</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loja_de_Angariacao__c.field-meta.xml
<CustomField>
    <fullName>Loja_de_Angariacao__c</fullName>
    <label>Loja de Angariação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albufeira</fullName>
            </value>
            <value>
                <fullName>Alfragide</fullName>
            </value>
            <value>
                <fullName>Almada</fullName>
            </value>
            <value>
                <fullName>Alta De Lisboa</fullName>
            </value>
            <value>
                <fullName>Alverca</fullName>
            </value>
            <value>
                <fullName>Amadora</fullName>
            </value>
            <value>
                <fullName>Aveiro</fullName>
            </value>
            <value>
                <fullName>Barcelos</fullName>
            </value>
            <value>
                <fullName>Barreiro</fullName>
            </value>
            <value>
                <fullName>Braga</fullName>
            </value>
            <value>
                <fullName>Bragança</fullName>
            </value>
            <value>
                <fullName>Caldas Da Rainha</fullName>
            </value>
            <value>
                <fullName>Carcavelos</fullName>
            </value>
            <value>
                <fullName>Cascais</fullName>
            </value>
            <value>
                <fullName>Castelo Branco</fullName>
            </value>
            <value>
                <fullName>Chaves</fullName>
            </value>
            <value>
                <fullName>Coimbra</fullName>
            </value>
            <value>
                <fullName>Colombo</fullName>
            </value>
            <value>
                <fullName>Évora</fullName>
            </value>
            <value>
                <fullName>Figueira Da Foz</fullName>
            </value>
            <value>
                <fullName>Funchal</fullName>
            </value>
            <value>
                <fullName>Gaia</fullName>
            </value>
            <value>
                <fullName>Gondomar</fullName>
            </value>
            <value>
                <fullName>Guarda</fullName>
            </value>
            <value>
                <fullName>Guimarães</fullName>
            </value>
            <value>
                <fullName>Leiria</fullName>
            </value>
            <value>
                <fullName>Loulé</fullName>
            </value>
            <value>
                <fullName>Loures</fullName>
            </value>
            <value>
                <fullName>Mafra</fullName>
            </value>
            <value>
                <fullName>Maia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_de_Conta_na_lead__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Conta_na_lead__c</fullName>
    <externalId>true</externalId>
    <label>Número de Conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/SCH_Service_Appointment_Details__c/SCH_Service_Appointment_Details__c.object-meta.xml
<CustomObject>
    <description>object to save details from SA
reason of cancelation
reason of completed</description>
    <label>Detalhe Marcação</label>
    <nameField>
        <displayFormat>SSD-{0000000}</displayFormat>
        <label>Detalhes Marcação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalhes Marcação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCH_Service_Appointment_Details__c/fields/SCH_OrigemMarcacao__c.field-meta.xml
<CustomField>
    <fullName>SCH_OrigemMarcacao__c</fullName>
    <label>Origem Marcação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Voz</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Service_Appointment_Details__c/fields/SCH_ServiceAppointment__c.field-meta.xml
<CustomField>
    <fullName>SCH_ServiceAppointment__c</fullName>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipName>Service_Appointment_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AppointmentEntryRest.cls
/**
 * @description       : REST API to create Service Appointments from external systems
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-09-03
 * @last modified by  : Felipe Mendonça
**/
@RestResource(urlMapping = '/appointments/*')
global without sharing class AppointmentEntryRest {

    @HttpPost
    global static void makePost() {
        RestResponse res = RestContext.response;
        ResponseDTO returnDTO = new ResponseDTO();
        resultDTO resultDTO = new resultDTO();

        try {
            // Request input
            RestRequest request = RestContext.request;
            String body = request.requestBody.toString();
            System.debug('body -->' + body);

            // Deserialize the appointment data
            AppointmentDTO appointment = (AppointmentDTO) JSON.deserialize(body, AppointmentDTO.class);

            // Validate input data
            if (appointment == null || appointment.lead == null || appointment.lead.extendedFields == null) {
                sendErrorResponse(res, 400, 'Missing required lead or extended fields information in the request.');
                return;
            }

            // Extract MDM Id from extended fields
            String mdmId;
            for (AppointmentDTO.ExtendedFieldDTO field : appointment.lead.extendedFields) {
                if (field.name.equalsIgnoreCase('Numero_de_Conta_na_lead__c')) {
                    mdmId = field.value;
                }
            }

            if (mdmId == null) {
                sendErrorResponse(res, 400, 'MDM ID is missing in the lead extended fields.');
                return;
            }

            List<MDM_Client> clients;

            if (Test.isRunningTest()){
                String clientString = '{"active":true, "addresses":[{"city":"MAIA","complementaryDeliveryAddress":"MORADIA COSTA DO SOL","countryCode":"PT","isContactPriority":true,"isQualitative":true,"postalCode":"4475","usages":[]}],"clientNumber":2462,"createdAt":"2022-07-06T14:25:01.124Z","creationStoreCode":"1","declaredStoreAttachement":"1","emailAddresses":[{"email":"teste@teste.com"}],"inhabitant":{"administrativeIdentifiers":{},"civility":"MS","firstName":"MAIA","lastName":"COSTA DO SOL"},"phones":[{"isContactPriority":false,"numberSF":"+351910974671","type":"LANDLINE"},{"isContactPriority":true,"number":"+351910974671"}],"universalClientNumber":"LMPT2462","updatedAt":"' + System.now().addDays(20).format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'') + '"},"_meta":{}}';
                MDM_Client c = (MDM_Client)JSON.deserialize(clientString, MDM_Client.class);
                clients = new List<MDM_Client>{c};
            }else{
                clients = c_PesquisaConta.getAccountsMdm(new List<String>{mdmId}, 'Nº de Cliente');
            }
            
            if (clients == null || clients.isEmpty()) {
                sendErrorResponse(res, 404, 'No client found with the given MDM ID.');
                return;
            }

            MDM_Client client = clients[0];
            System.debug(client);

            // Validate assigned resources
            if (appointment.assignedResources == null || appointment.assignedResources.isEmpty()) {
                sendErrorResponse(res, 400, 'Assigned resources are missing in the request.');
                return;
            }

            ServiceAppointment sa = createServiceAppointmentLead(client, appointment);

            // Check for available appointment slots
            if (!hasAppointmentSlots(sa)) {
                sendErrorResponse(res, 409, 'Appointment slot not available.');
                return;
            }
            // Calculate Duration
            Decimal durationInHours = (sa.SchedEndTime.getTime() - sa.schedStartTime.getTime())/1000/60/60;
            sa.duration = durationInHours;
            System.debug(sa);
            insert sa; // Insert ServiceAppointment record
            createAssignedResource(sa, appointment.assignedResources[0].serviceResourceId);
            createSADetails(sa);

            resultDTO.serviceAppointmentId = sa.Id;
            resultDTO.parentRecordId = sa.ParentRecordId;
            returnDTO.result = resultDTO;

            res.statusCode = 201;
            res.responseBody = Blob.valueOf(JSON.serialize(returnDTO));

        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            sendErrorResponse(res, 500, 'Internal Server Error: ' + e.getMessage());
        }
    }

    public static void createSADetails(ServiceAppointment sa) {
        SCH_Service_Appointment_Details__c saDetails = new SCH_Service_Appointment_Details__c();
        saDetails.SCH_ServiceAppointment__c = sa.Id;
        saDetails.SCH_OrigemMarcacao__c = 'Web';
        insert saDetails;
    }

    private static Boolean isClienteEmpresa(MDM_Client client){
        System.debug(client.inhabitant.lastName);
        return String.isBlank(client.inhabitant.lastName) || client.inhabitant.lastName == '-'; //Clientes empresa não têm lastName. Mesmo critério usado em c_PesquisaConta.upsertAccountSF
    }

    private static ServiceAppointment createServiceAppointmentLead(MDM_Client client, AppointmentDTO appointment) {
        ServiceAppointment sa = new ServiceAppointment();
        sa = (ServiceAppointment) JSON.deserialize(JSON.serialize(appointment.serviceAppointment), ServiceAppointment.class);
        sa.IsAnonymousBooking = true;
        sa.OwnerId = getUserFromServiceResource(appointment.assignedResources[0].serviceResourceId);
        sa.SCH_Service_Resource__c = appointment.assignedResources[0].serviceResourceId;

        // Upsert Lead from client data
        Lead lead = new Lead();
        System.debug('Cliente: '+ client );
        lead.Numero_de_Conta_na_lead__c = String.valueOf(client.clientNumber);
        if(isClienteEmpresa(client)){
            lead.FirstName = client.inhabitant.FirstName;
            lead.LastName = '.';
            lead.NIF__c = String.isEmpty(client.professionalOrganization.administrativeCodes.nif) ? '': client.professionalOrganization.administrativeCodes.nif;

            for (MDM_Client.Member member : client.members){
                if (member.isLegalRepresentative){
                    for (MDM_Client.EmailAddress emailAddress : member.emailAddresses){
                        if (emailAddress.isContactPriority)
                            lead.Email = emailAddress.email;
                            sa.Email = lead.email;
                        break;
                    }
                    for (MDM_Client.Phone phone : member.phones){
                        if (phone.isContactPriority)
                            lead.MobilePhone = phone.numberSF != null ? phone.numberSF : '';
                            lead.Phone = phone.numberSF != null ? phone.numberSF : '';
                            sa.Phone = lead.Phone;
                        break;
                    }
                    break;
                }
            }
            System.debug('Lead Cliente Profissional: ' + lead);

        } else {
            lead.FirstName = client.inhabitant.firstName;
            lead.LastName = client.inhabitant.lastName;
            lead.Email = client.emailAddresses.isEmpty() ? 'emailnotfound@email.com' : client.emailAddresses[0].email;
            lead.NIF__c = String.isEmpty(client.inhabitant.administrativeIdentifiers.nif) ? '': client.inhabitant.administrativeIdentifiers.nif;
            if (client.phones.isEmpty()){
                lead.MobilePhone = '';
                lead.Phone = '';
            }else{
                lead.MobilePhone = client.phones[0].numberSF != null ? client.phones[0].numberSF : '';
                lead.Phone = client.phones[0].numberSF != null ? client.phones[0].numberSF : '';
            }
            sa.Email = lead.email;
            sa.Phone = lead.Phone;
            System.debug('Lead Cliente Particular: ' + lead);
        }

        List<ServiceTerritory> serviceTerritoryList = [SELECT Id, Name, ParentTerritory.Name FROM ServiceTerritory WHERE Id =: appointment.serviceAppointment.serviceTerritoryId];
        String lojaDeAngariacao = '';
        if(!serviceTerritoryList.isEmpty()){
            String parentTerritoryName = serviceTerritoryList[0].ParentTerritory.Name;
            lojaDeAngariacao = String.isBlank(parentTerritoryName) ? serviceTerritoryList[0].Name : parentTerritoryName;
        }

        if (String.isBlank(lead.Canal_de_Interacao__c))
            lead.Canal_de_Interacao__c = 'Scheduler Online';
        if (String.isBlank(lead.Loja_de_Angariacao__c))
            lead.Loja_de_Angariacao__c = lojaDeAngariacao;

        insert lead;

        // Associate SA with Lead
        sa.ParentRecordId = lead.Id;
        return sa;
    }

    private static Id getUserFromServiceResource(Id serviceResourceId){
        List<ServiceResource> serviceResources = [SELECT Id, RelatedRecordId FROM ServiceResource WHERE Id =: serviceResourceId];
        if (serviceResources.size() == 0) return UserInfo.getUserId();
        return serviceResources[0].RelatedRecordId;
    }

    private static Boolean hasAppointmentSlots(ServiceAppointment sa) {
        Integer reservedTime = sa.WorkType.BlockTimeAfterAppointment == null ? 15 : Integer.valueOf(sa.WorkType.BlockTimeAfterAppointment);
        DateTime adjustedEndTime = sa.SchedEndTime.addMinutes(reservedTime);
        DateTime adjustedStartTime = sa.SchedStartTime.addMinutes(-reservedTime);
        List<ServiceAppointment> existingAppointments = [SELECT Id, SchedStartTime, SchedEndTime FROM ServiceAppointment WHERE 
                                                         SchedStartTime < :adjustedEndTime AND
                                                         SchedEndTime > :adjustedStartTime AND 
                                                         EngagementChannelTypeId = :sa.EngagementChannelTypeId AND
                                                         ServiceTerritoryId = :sa.ServiceTerritoryId AND
                                                         SCH_Service_Resource__c = :sa.SCH_Service_Resource__c AND
                                                         Status != 'Canceled'];
        
        for (ServiceAppointment existing : existingAppointments) {
            if (existing.SchedStartTime < adjustedEndTime && existing.SchedEndTime > adjustedStartTime) {
                return false; // Conflict found
            }
        }
        return true;
    }

    public static void createAssignedResource(ServiceAppointment sa, String serviceResourceId) {
            // Create AssignedResource record to link ServiceAppointment with the scheduler resource
            AssignedResource ar = new AssignedResource();
            ar.ServiceAppointmentId = sa.Id;
            ar.ServiceResourceId = serviceResourceId;
            ar.isPrimaryResource = true;
            ar.isRequiredResource = true;
            insert ar; // Insert AssignedResource record to establish the link
    }

    private static void sendErrorResponse(RestResponse res, Integer statusCode, String message) {
        res.statusCode = statusCode;
        res.responseBody = Blob.valueOf(JSON.serialize(new ErrorResponse(message)));
    }

    public class ResponseDTO {
        public resultDTO result { get; set; }
    }

    public class resultDTO {
        public List<String> assignedResourceIds { get; set; }
        public String parentRecordId { get; set; }
        public String serviceAppointmentId { get; set; }
    }

    public class ErrorResponse {
        public String error { get; set; }
        public ErrorResponse(String message) {
            error = message;
        }
    }
}