force-app/main/default/objects/Lead/fields/Canal_de_Interacao__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Interacao__c</fullName>
    <inlineHelpText>Scheduler Online - cliente agenda online em autonomia (independente se o cliente escolhe fazer presencial ou online)                    
Scheduler Loja - cliente vai à loja, o agendamento é feito pela loja (independente se o cliente escolhe fazer presencial ou online)                 
Scheduler Telefone - cliente liga a pedir para agendar                   
Loja - venda simples em loja (não é agendamento de projeto)                   
VAD - venda simples pela VAD (não é agendamento de projeto)</inlineHelpText>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduler Online</fullName>
            </value>
            <value>
                <fullName>Scheduler Loja</fullName>
            </value>
            <value>
                <fullName>Scheduler Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>VAD</fullName>
            </value>
            <value>
                <fullName>Profissional</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Importação</fullName>
                <isActive>false</isActive>
                <label>Importação</label>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Online</fullName>
                <isActive>false</isActive>
                <label>Online</label>
            </value>
            <value>
                <fullName>Redes Sociais</fullName>
                <isActive>false</isActive>
                <label>Redes Sociais</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loja_de_Angariacao__c.field-meta.xml
<CustomField>
    <fullName>Loja_de_Angariacao__c</fullName>
    <label>Loja de Angariação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albufeira</fullName>
            </value>
            <value>
                <fullName>Alfragide</fullName>
            </value>
            <value>
                <fullName>Almada</fullName>
            </value>
            <value>
                <fullName>Alta De Lisboa</fullName>
            </value>
            <value>
                <fullName>Alverca</fullName>
            </value>
            <value>
                <fullName>Amadora</fullName>
            </value>
            <value>
                <fullName>Aveiro</fullName>
            </value>
            <value>
                <fullName>Barcelos</fullName>
            </value>
            <value>
                <fullName>Barreiro</fullName>
            </value>
            <value>
                <fullName>Braga</fullName>
            </value>
            <value>
                <fullName>Bragança</fullName>
            </value>
            <value>
                <fullName>Caldas Da Rainha</fullName>
            </value>
            <value>
                <fullName>Carcavelos</fullName>
            </value>
            <value>
                <fullName>Cascais</fullName>
            </value>
            <value>
                <fullName>Castelo Branco</fullName>
            </value>
            <value>
                <fullName>Chaves</fullName>
            </value>
            <value>
                <fullName>Coimbra</fullName>
            </value>
            <value>
                <fullName>Colombo</fullName>
            </value>
            <value>
                <fullName>Évora</fullName>
            </value>
            <value>
                <fullName>Figueira Da Foz</fullName>
            </value>
            <value>
                <fullName>Funchal</fullName>
            </value>
            <value>
                <fullName>Gaia</fullName>
            </value>
            <value>
                <fullName>Gondomar</fullName>
            </value>
            <value>
                <fullName>Guarda</fullName>
            </value>
            <value>
                <fullName>Guimarães</fullName>
            </value>
            <value>
                <fullName>Leiria</fullName>
            </value>
            <value>
                <fullName>Loulé</fullName>
            </value>
            <value>
                <fullName>Loures</fullName>
            </value>
            <value>
                <fullName>Mafra</fullName>
            </value>
            <value>
                <fullName>Maia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_de_Conta_na_lead__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Conta_na_lead__c</fullName>
    <externalId>true</externalId>
    <label>Número de Conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/classes/AppointmentDTO.cls
/* Example JSON

{
  "serviceAppointment" : {
    "serviceTerritoryId" : "0HhAe0000001ENVKA2",
    "schedStartTime" : "2024-11-11T10:15:00.000Z",
    "schedEndTime" : "2024-11-11T13:15:00.000Z",
    "workTypeId" : "08qAe0000003PzZIAU",
    "additionalInformation" : null,
    "engagementChannelTypeId" : "0eFAe000000034LMAQ",
    "extendedFields" : [ {
      "name" : "IsAnonymousBooking",
      "value" : "false"
    } ],
    "description" : "Dentro de quanto tempo pretende iniciar a instalação da sua nova cozinha?: O mais brevemente possível/nQual o orçamento disponível para a sua nova cozinha (incluindo mobiliário e equipamentos)?: 2.000 € - 3.000 €/nQual é o estilo que pretende para a sua cozinha?: Moderno/nQuem irá instalar a sua cozinha?: Ainda não sei/n"
  },
  "lead" : {
    "firstName" : "firstName",
    "lastName" : "lastName",
    "phone" : "999999999",
    "email" : "70150193@email.com",
    "company" : null,
    "extendedFields" : [ {
      "name" : "Loja_de_Angariacao__c",
      "value" : "Alfragide"
    }, {
      "name" : "Canal_de_Interacao__c",
      "value" : "Scheduler Online"
    }, {
      "name" : "Numero_de_Conta_na_lead__c",
      "value" : "70150193"
    } ]
  },
  "assignedResources" : [ {
    "serviceResourceId" : "0HnAe0000004OzpKAE",
    "isRequiredResource" : true,
    "isPrimaryResource" : true
  } ]
}

*/


public with sharing class AppointmentDTO {
    public ServiceAppointmentDTO serviceAppointment { get; set; }
    public LeadDTO lead { get; set; }
    public list<AssignedResourceDTO> assignedResources {get;set;}

    public class ServiceAppointmentDTO {
        public String workTypeId { get; set; }
        public String serviceTerritoryId { get; set; }
        public String engagementChannelTypeId { get; set; }
        public Datetime schedStartTime { get; set; }
        public Datetime schedEndTime { get; set; }
        public String parentRecordId { get; set; }
        public String street { get; set; }
        public String city { get; set; }
        public String state { get; set; }
        public String postalCode { get; set; }
        public String country { get; set; }
        public String appointmentType { get; set; }
        public String appointmentMode { get; set; }
        public String attendeeLimit { get; set; }
        public String description {get; set; }
    }

    public class LeadDTO {
        public String firstName { get; set; }
        public String lastName { get; set; }
        public String phone { get; set; }
        public String email { get; set; }
        public String company { get; set; }
        public List<ExtendedFieldDTO> extendedFields { get; set; }
    }

    public class ExtendedFieldDTO {
        public String name { get; set; }
        public String value { get; set; }
    }

    public class AssignedResourceDTO{
      public String serviceResourceId {get;set;}
      public Boolean isRequiredResource {get;set;}
      public Boolean isPrimaryResource {get;set;}
    }
  }