force-app/main/default/objects/PerformanceLog__c/PerformanceLog__c.object-meta.xml
<CustomObject>
    <label>PerformanceLog</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>PerformanceLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PerformanceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PerformanceLogEntry__c/PerformanceLogEntry__c.object-meta.xml
<CustomObject>
    <label>PerformanceLogEntry</label>
    <nameField>
        <displayFormat>PLE-{0000}</displayFormat>
        <label>PerformanceLogEntry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PerformanceLogEntries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PerformanceLogEntry__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>In ms.</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLogEntry__c/fields/PerformanceLog__c.field-meta.xml
<CustomField>
    <fullName>PerformanceLog__c</fullName>
    <label>PerformanceLog</label>
    <referenceTo>PerformanceLog__c</referenceTo>
    <relationshipLabel>PerformanceLogEntries</relationshipLabel>
    <relationshipName>PerformanceLogEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PerformanceLogBatch.cls
/**
 * @description       : Batch class to handle PerformanceLog__c records and delegate entry processing to PerformanceLogEntriesBatch
 * @author            : Ricardo Simões
 * @group             :
 * @last modified on  : 2026-01-12
 * @last modified by  : Ricardo Simões
**/
public with sharing class PerformanceLogBatch implements Database.Batchable<PerformanceLogBatch.PerformanceLogWrapper>, Database.Stateful {

    private List<PerformanceLogBatch.PerformanceLogWrapper> logWrapperList;
    private List<PerformanceLogEntry__c> entriesToInsert = new List<PerformanceLogEntry__c>();
    private Map<String, String> insertedLogsByToken = new Map<String, String>();

    public PerformanceLogBatch(List<PerformanceLogBatch.PerformanceLogWrapper> logWrapperList) {
        this.logWrapperList = logWrapperList;
    }

    public Iterable<PerformanceLogBatch.PerformanceLogWrapper> start(Database.BatchableContext bc) {
        return this.logWrapperList;
    }

    public void execute(Database.BatchableContext bc, List<PerformanceLogBatch.PerformanceLogWrapper> scope) {
        // Insert PerformanceLog__c records
        List<PerformanceLog__c> logsToInsert = new List<PerformanceLog__c>();

        for (PerformanceLogBatch.PerformanceLogWrapper wrapper : scope) {
            PerformanceLog__c log = wrapper.log;
            logsToInsert.add(log);
        }

        insert logsToInsert;
        System.debug('Inserted ' + logsToInsert.size() + ' performance logs.');

        // Map inserted logs back to their wrappers
        for(PerformanceLog__c log : logsToInsert) {
            String Token = log.Token__c;
            insertedLogsByToken.put(Token, log.Id);
        }
    }

    public void finish(Database.BatchableContext bc) {
        try {
            for (Integer i = 0; i < logWrapperList.size(); i++) {
                String PerformanceId = insertedLogsByToken.get(logWrapperList[i].log.Token__c);

                if (logWrapperList[i].entries != null) {
                    for (PerformanceLog.PerformanceLogEntry entry : logWrapperList[i].entries) {
                            PerformanceLogEntry__c logEntryObj = new PerformanceLogEntry__c();
                            logEntryObj.PerformanceLog__c = PerformanceId;
                            logEntryObj.Description__c = entry.description;
                            logEntryObj.TimeStamp__c = entry.timeStamp;
                            logEntryObj.Duration__c = entry.duration;
                            logEntryObj.Token__c = logWrapperList[i].log.Token__c;

                            entriesToInsert.add(logEntryObj);
                    }
                }
            }
           
            if (!entriesToInsert.isEmpty()) {
                System.debug('Inserting ' + entriesToInsert.size() + ' performance log entries.');
                Database.executeBatch(new PerformanceLogEntriesBatch(entriesToInsert), 200);
            }
            
        } catch (Exception e) {
            ErrorLog.createErrorLogList('PerformanceLogBatch.finish', e.getMessage(), e.getLineNumber().toString(), 'PerformanceLogBatch.finish', e.getStackTraceString(), e.getTypeName());
        }
    }
    
    public class PerformanceLogWrapper {
        public PerformanceLog__c log;
        public List<PerformanceLog.PerformanceLogEntry> entries = new List<PerformanceLog.PerformanceLogEntry>();
    }
}