force-app/main/default/objects/AppointmentSlot__c/AppointmentSlot__c.object-meta.xml
<CustomObject>
    <label>Appointment Slot</label>
    <nameField>
        <displayFormat>SLOT-{00000}</displayFormat>
        <label>Slot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Slots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AppointmentSlot__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start Time</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AppointmentSlotExpiryBatch.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-09-12
 * @last modified by  : Hersilio Belini de Oliveira
**/
global class AppointmentSlotExpiryBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Available__c
            FROM AppointmentSlot__c
            WHERE Available__c = TRUE
              AND StartTime__c < :Datetime.now()
        ]);
    }

    global void execute(Database.BatchableContext bc, List<AppointmentSlot__c> scope) {
        for (AppointmentSlot__c slot : scope) {
            slot.Available__c = false;
        }
        if (!scope.isEmpty()) {
            Database.update(scope, false);
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}