force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/LM_Autocrat_Process_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Autocrat Process Setting</label>
    <pluralLabel>Autocrat Process Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/Email_Attachment_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Attachment_Template__c</fullName>
    <label>Email Attachment Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LM_InvocableSaveToSF.cls
public without sharing class LM_InvocableSaveToSF {
    
    @invocableMethod(label='Save PDF to Salesforce' description='Save the PDF to the current context record')
    public static void savePDFToRecord(List<FlowInput> input){
        for (FlowInput i : input){
            String fileName = i.order.OrderNumber + ' - ' + i.mdt.Attachment_Name__c;
            Id existingFileId = LM_PdfCreator.fileExists(fileName, i.order.Id);
            if (existingFileId != null) {
                LM_PdfCreator.removeFile(existingFileId);
            }

            Blob pdfBlob = LM_PdfCreator.createPdfBlob(i.mdt.Email_Attachment_Template__c, i.order.Id);
            LM_PdfCreator.savePdfToSF(pdfBlob, i.order.Id, fileName);
        }
    }

    public class FlowInput{
        @InvocableVariable (label='Autocrat Process Setting' description='The Autocrat Process Setting metadata record')
        public LM_Autocrat_Process_Setting__mdt mdt;
        @InvocableVariable (label='Order' description='The Order record to which the PDF will be attached')
        public Order order;
    }
}