force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/LM_Autocrat_Process_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Autocrat Process Setting</label>
    <pluralLabel>Autocrat Process Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/GDrive_Process_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>GDrive_Process_Folder_Name__c</fullName>
    <label>GDrive Process Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/Order_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Record_Type__c</fullName>
    <label>Order Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LM_GDrive_File_Link__c/LM_GDrive_File_Link__c.object-meta.xml
<CustomObject>
    <label>GDrive File</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>GDrive File Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDrive Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LM_GDrive_File_Link__c/fields/File_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Url__c</fullName>
    <label>File Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/LM_GDrive_File_Link__c/fields/fileId__c.field-meta.xml
<CustomField>
    <fullName>fileId__c</fullName>
    <label>FileId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LM_GDrive_File_Link__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Anexos GDrive</relationshipLabel>
    <relationshipName>GDrive_File_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LM_Store__c/LM_Store__c.object-meta.xml
<CustomObject>
    <label>Loja</label>
    <nameField>
        <label>Nome da Loja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lojas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LM_Store__c/fields/GDrive_Folder__c.field-meta.xml
<CustomField>
    <fullName>GDrive_Folder__c</fullName>
    <label>Pasta GDrive</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LM_Store__c/fields/Store_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LM_GDriveUrlController.cls
public without sharing class LM_GDriveUrlController {

    @auraEnabled
    public static LM_GDrive_File_Link__c createUrl(String filename, String url, String orderId, String fileId){
        LM_GDrive_File_Link__c link = new LM_GDrive_File_Link__c();
        link.File_Name__c = filename;
        link.File_Url__c = url;
        link.Order__c = orderId;
        link.fileId__c = fileId;
        
        insert link;
        return link;
    }
    
    public static String getStoreFolderName(String orderId){
        List<Order> order = [SELECT Id, Store__c FROM Order WHERE Id = :orderId LIMIT 1];
        List<LM_Store__c> store = [SELECT Id, Store_API_Name__c, GDrive_Folder__c from LM_Store__c WHERE Id = :order[0].Store__c LIMIT 1];
        return store[0].GDrive_Folder__c;
    }
    
    public static String getProcessFolderName(String orderRecordType){
        System.Debug('orderRecordType: ' + orderRecordType);
        List<LM_Autocrat_Process_Setting__mdt> mdt = [SELECT Id, Order_Record_Type__c, GDrive_Process_Folder_Name__c FROM LM_Autocrat_Process_Setting__mdt WHERE Order_Record_Type__c =: orderRecordType];
        return mdt[0].GDrive_Process_Folder_Name__c;
    }
    
    //returns Store Folder Name from userId
    @auraEnabled
    public static String getGDriveFolderId(Id orderId, String orderRecordType){
        String storeFolderName = getStoreFolderName(orderId);
        String processFolderName = getProcessFolderName(orderRecordType);
        String result = LM_GoogleDriveAPIController.getGDriveFolderId(processFolderName, storeFolderName);
        if (String.isEmpty(result)) return null;     
        return result;
    }
}