force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/LM_Autocrat_Process_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Autocrat Process Setting</label>
    <pluralLabel>Autocrat Process Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/SMS_From__c.field-meta.xml
<CustomField>
    <fullName>SMS_From__c</fullName>
    <label>SMS From</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/LM_Invocable_Send_Token.cls
public without sharing class LM_Invocable_Send_Token {
   
    @InvocableMethod(label='Send SMS')
    public static void sendToken(List<FlowInput> input){
        for (FlowInput i: input){
            Order order = i.order;
            LM_Autocrat_Process_Setting__mdt mdt = i.metadata;   
            EmailTemplate et = i.emailTemplate;
            
            Account acc = [SELECT Id, Phone from Account WHERE Id =: order.AccountId];
            
            String SMSFrom = mdt.SMS_From__c;
            String SMSTo = acc.Phone.contains('+351') ? acc.Phone : '+351' + acc.Phone;
            String SMSBody = Messaging.renderEmailTemplate(null, order.Id, new List<String>{et.Body})[0].getMergedBody();
            
            if (Test.isRunningTest()){
                return;
            }
            System.enqueueJob(new LM_SendSMS(SMSFrom, SMSTo, SMSBody));   
        }
    }

    public class FlowInput{

        @InvocableVariable
        public Order order;
        @InvocableVariable
        public LM_Autocrat_Process_Setting__mdt metadata;
        @InvocableVariable
        public EmailTemplate emailTemplate;

    }
}