force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/LM_Autocrat_Process_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Autocrat Process Setting</label>
    <pluralLabel>Autocrat Process Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LM_Autocrat_Process_Setting__mdt/fields/Email_Attachment_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Attachment_Template__c</fullName>
    <label>Email Attachment Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LM_InvocableGDriveSave.cls
public without sharing class LM_InvocableGDriveSave {
	// @InvocableMethod (label='Save File to GDrive')
    // public static void saveFileToGDrive(List<FlowInput> input){
    //     for (FlowInput i : input){
    //         Blob pdfContent = LM_PdfCreator.createPdfBlob(i.mdt.Email_Attachment_Template__c, i.order.Id);
    //         if(Test.isRunningTest()) continue;
    //         System.enqueueJob(new LM_InvocableSendEmail.GDriveCaller(pdfContent, i.mdt, i.order));
    //     }
    // }
    
    // public class FlowInput{
        
    //     @InvocableVariable
    //     public LM_Autocrat_Process_Setting__mdt mdt;
    //     @InvocableVariable
    //     public Order order;
    // }
}